collections:
  projects:
    output: true
    permalink: /projects/:name/

title: "Home"
author:
  name: Clara Peiret-García
  email: c.peiret-garcia@ucl.ac.com
  github_username: cpeiretgarcia

description: 
theme: minima
baseurl: "" # leave empty for user/organization site
url: "https://cpeiretgarcia.github.io"



header_pages:
  - about.md
  - projects.md
