title: Dr. Your Name
description: Academic personal website
theme: minima
baseurl: "" # leave empty for user/organization site
url: "https://yourusername.github.io" # replace with your GitHub Pages URL

# Optional settings
email: your@email.com
github_username: yourusername
