title: 
description: 
theme: minima
baseurl: "" # leave empty for user/organization site
url: "https://cpeiretgarcia.github.io" # replace with your GitHub Pages URL

# Optional settings
email: c.peiret-garcia@ucl.ac.uk
github_username: cpeiretgarcia

header_pages:
  - about.md
  - projects.md
