collections:
  projects:
    output: true
    permalink: /projects/:name/

title: "Home"
description: 
theme: minima
baseurl: "" # leave empty for user/organization site
url: "https://cpeiretgarcia.github.io"

email: c.peiret-garcia@ucl.ac.uk
github_username: cpeiretgarcia

header_pages:
  - about.md
  - projects.md
